const countryFlags = {
    'Afghanistan': 'af',
    'Albania': 'al',
    'Algeria': 'dz',
    'Andorra': 'ad',
    'Angola': 'ao',
    'Argentina': 'ar',
    'Armenia': 'am',
    'Australia': 'au',
    'Austria': 'at',
    'Azerbaijan': 'az',
    'Bahamas': 'bs',
    'Bahrain': 'bh',
    'Bangladesh': 'bd',
    'Belarus': 'by',
    'Belgium': 'be',
    'Belize': 'bz',
    'Benin': 'bj',
    'Bhutan': 'bt',
    'Bosnia and Herzegovina': 'ba',
    'Brazil': 'br',
    'Bulgaria': 'bg',
    'Burkina Faso': 'bf',
    'Cambodia': 'kh',
    'Cameroon': 'cm',
    'Canada': 'ca',
    'Chile': 'cl',
    'China': 'cn',
    'Colombia': 'co',
    'Costa Rica': 'cr',
    'Croatia': 'hr',
    'Cuba': 'cu',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Dominican Republic': 'do',
    'Egypt': 'eg',
    'El Salvador': 'sv',
    'Estonia': 'ee',
    'Ethiopia': 'et',
    'Fiji': 'fj',
    'Finland': 'fi',
    'France': 'fr',
    'Georgia': 'ge',
    'Germany': 'de',
    'Ghana': 'gh',
    'Greece': 'gr',
    'Guatemala': 'gt',
    'Guinea': 'gn',
    'Haiti': 'ht',
    'Honduras': 'hn',
    'Hungary': 'hu',
    'Iceland': 'is',
    'India': 'in',
    'Indonesia': 'id',
    'Iran': 'ir',
    'Iraq': 'iq',
    'Italy': 'it',
    'Ivory Coast': 'ci',
    'Jamaica': 'jm',
    'Japan': 'jp',
    'Jordan': 'jo',
    'Kazakhstan': 'kz',
    'Kenya': 'ke',
    'Kosovo': 'xk',
    'Kuwait': 'kw',
    'Kyrgyzstan': 'kg',
    'Laos': 'la',
    'Latvia': 'lv',
    'Lebanon': 'lb',
    'Liberia': 'lr',
    'Libya': 'ly',
    'Lithuania': 'lt',
    'Luxembourg': 'lu',
    'Malaysia': 'my',
    'Mali': 'ml',
    'Malta': 'mt',
    'Mexico': 'mx',
    'Moldova': 'md',
    'Monaco': 'mc',
    'Montenegro': 'me',
    'Morocco': 'ma',
    'Myanmar': 'mm',
    'Nepal': 'np',
    'Netherlands': 'nl',
    'New Caledonia': 'nc',
    'New Zealand': 'nz',
    'Nicaragua': 'ni',
    'Niger': 'ne',
    'Nigeria': 'ng',
    'North Macedonia': 'mk',
    'Norway': 'no',
    'Oman': 'om',
    'Pakistan': 'pk',
    'Panama': 'pa',
    'Papua New Guinea': 'pg',
    'Peru': 'pe',
    'Philippines': 'ph',
    'Poland': 'pl',
    'Puerto Rico': 'pr',
    'Qatar': 'qa',
    'Russia': 'ru',
    'Rwanda': 'rw',
    'San Marino': 'sm',
    'Saudi Arabia': 'sa',
    'Senegal': 'sn',
    'Serbia': 'rs',
    'Sierra Leone': 'sl',
    'Singapore': 'sg',
    'Slovenia': 'si',
    'Solomon Islands': 'sb',
    'South Africa': 'za',
    'South Korea': 'kr',
    'Spain': 'es',
    'Sri Lanka': 'lk',
    'Sudan': 'sd',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'Syria': 'sy',
    'Taiwan': 'tw',
    'Tajikistan': 'tj',
    'Tanzania': 'tz',
    'Thailand': 'th',
    'Togo': 'tg',
    'Tunisia': 'tn',
    'Turkey': 'tr',
    'Turkmenistan': 'tm',
    'Uganda': 'ug',
    'Ukraine': 'ua',
    'United Arab Emirates': 'ae',
    'United Kingdom': 'gb',
    'United States': 'us',
    'Uzbekistan': 'uz',
    'Vatican City': 'va',
    'Venezuela': 've',
    'Vietnam': 'vn',
    'Yemen': 'ye',
    'Universal Time Coordinated': 'un' // Using UN flag for UTC
};